name: Build xk6 telegram

on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.18

    - name: Install xk6
      run: go install go.k6.io/xk6/cmd/xk6@latest

    - name: Build xk6
      run: xk6 build --with github.com/Maksimall89/xk6-telegram=.
